create html+css
ValentinDankovtsev/html-taskMaket pull request #1
Opened 2021-01-20 20:09 UTC by ValentinDankovtsev

https://rawcdn.githack.com/ValentinDankovtsev/html-taskMaket/cfc989d8947f1512760790f398df876e8a9a43a8/index.html

2021-01-21 15:28 UTC, AntiHero commented
отлично), можешь на завтра записываться на консультацию, разберём)

2021-01-22 19:30 UTC, AntiHero requested changes

2021-01-22 19:30 UTC, AntiHero commented on index.html
> +      <div class="blue">
можно поинтереснее названия для класса придумать?)

2021-01-22 19:30 UTC, AntiHero commented on index.html
> +        <img src="img.jpg" alt="Картинка" />
для картинок, равно как и для стилей, иконок, js файлов и т.д. нужно использовать отдельные директории/папки, чтобы все твои файлы не были разбросаны в корне, а хранились отдельно, каждый в своей директории

2021-01-22 19:30 UTC, AntiHero commented on index.html
> +        <h1>SNOWBOARDING PRESENTS:"BIG BAND.БЕРИ КАТАЙ"</h1>
почему не использовал бэм?

2021-01-22 19:30 UTC, AntiHero commented on index.html
> +        <div class="navi1">
опять же название класса navi1 что это значит и как логически оно относится к твоему блоку?

2021-01-22 19:30 UTC, AntiHero requested changes

2021-01-22 19:30 UTC, AntiHero commented on index.html
> +<html lang="en">
ru

2021-01-23 16:44 UTC, AntiHero requested changes

2021-01-23 16:44 UTC, AntiHero commented on .github/workflows/deploy-gh-pages.yml
> +      - name: Install Packages
а зачем здесь тебе делать install packages?)если все твои packages это devDependencies , которые используются только при разработке? для прогона линтеров это имеет смысл, а здесь нет

2021-01-23 16:44 UTC, AntiHero commented on src/index.html
> +          <h2 class="main__article__block--heading2">Как выбрать?</h2>
модификатор,  в данном случае --heading2 должен отвечать на вопрос "какой"? главный, синий, нижний, большой и т.д., мне кажется этот модификатор отвечает на впорос "что?"

2021-01-23 16:44 UTC, AntiHero commented on src/index.html
> +        <div class="main__article__block">
так писать некорректно, получается у  тебя блок__элемент1__элемент2, элемент не может выступать в качестве блока для другого элемента (т.е элемент1__элемент2 - это неверная запись)
т.е. скорее всего ты хотел назвать этот div (элемент) articleblock, тогда это делается так `article-block` и название класса для этого элемента будет` main__article-block` или можно просто `main__article` или представить этот div не в качестве элемента, а в качестве блока main-article

2021-01-23 16:44 UTC, AntiHero commented on src/index.html
> +          <p class="main__article__block__content">
тогда корректный вариант класса по бэм для  этого параграфа будет `main__article-paragraph` или `main-article__paragraph`, `main-article__content` и т.д.

2021-01-23 16:44 UTC, AntiHero commented on src/styles/footer.css
> +  color: black;
старайся использовать один тип для цветов, например с хэшсимволом или rgb / rgba,  здорово если для цветов (и  для часто используемых констант) придумаешь переменные https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2021-01-23 16:44 UTC, AntiHero commented on src/styles/header.css
> +  max-height: 100%;
здесь это свойсто не нужно

2021-01-23 16:44 UTC, AntiHero commented on src/styles/main.css
> +  min-height: calc(100vh - 40vh);
тут после min-height можно смело писать height: 100%

2021-01-23 16:44 UTC, AntiHero commented on src/styles/main.css
> +  flex: 0 0 20vw;
а почему flex: 0 **0** ? что значит второй параметр во flex свойстве?

2021-01-23 16:44 UTC, AntiHero commented on src/styles/style.css
> +  padding: 1em;
тут можно смело использовать px, так как ты не работаешь с font, а em рассчитывается относительно шрифта ближайшего родительского элемента

2021-01-24 11:24 UTC, ValentinDankovtsev commented on .github/workflows/deploy-gh-pages.yml
> +      - name: Install Packages
build удалил, а это нет)

2021-01-24 11:24 UTC, ValentinDankovtsev commented on src/index.html
> +          <h2 class="main__article__block--heading2">Как выбрать?</h2>
ок,исправил

2021-01-24 11:24 UTC, ValentinDankovtsev commented on src/index.html
> +        <div class="main__article__block">
ок

2021-01-24 11:24 UTC, ValentinDankovtsev commented on src/index.html
> +          <p class="main__article__block__content">
переделал заново

2021-01-24 11:25 UTC, ValentinDankovtsev commented on src/styles/footer.css
> +  color: black;
сделал переменные

2021-01-24 11:25 UTC, ValentinDankovtsev commented on src/styles/header.css
> +  max-height: 100%;
хорошо

2021-01-24 11:25 UTC, ValentinDankovtsev commented on src/styles/main.css
> +  min-height: calc(100vh - 40vh);
ок)

2021-01-24 11:27 UTC, ValentinDankovtsev commented on src/styles/main.css
> +  flex: 0 0 20vw;
это https://developer.mozilla.org/ru/docs/Web/CSS/flex-shrink
flex-shrink — свойство CSS, которое определяет фактор сжатия flex-элемента. Flex-элементы будут заполнять контейнер в зависимости от значения flex-shrink, когда стандартная ширина flex-элементов шире, чем flex-контейнер.

2021-01-24 11:28 UTC, ValentinDankovtsev commented on src/styles/style.css
> +  padding: 1em;
ок)

2021-01-24 13:25 UTC, AntiHero requested changes

2021-01-24 13:25 UTC, AntiHero commented on .gitignore
> +node_modules
.gitignore добавляешь в .gitignore и отсюда удаляеешь

2021-01-24 13:25 UTC, AntiHero commented on src/index.html
> +          class="header__image--main"
--main тут у тебя модификатор так? если ты откроешь бэм, то увидишь, что  [Модификатор нельзя использовать самостоятельно](https://ru.bem.info/methodology/quick-start/), поэтому что тут можно сделать, например придумать базовый класса для своего img` image`
тогда структура будет выглядеть так
```html
<div class="header__image">
    <img
      class="image image--main"
       src="images/img.jpg"
       alt="Сноубордист"
    />
</div>
```

2021-01-24 13:25 UTC, AntiHero commented on src/index.html
> +        <h1 class="header__title--main">
тоже самое тут, базовый класс + базовый класс--модификатор
но опять же, модификаторы имеет смысл использовать тогда, когда это действительно необходимо, просто так их добавлять - лишняя работа

2021-01-24 13:25 UTC, AntiHero commented on src/styles/footer.css
> +  flex: 0 0 20vw;
опять же, почему flex: 0  **0** 20vw? почему 0 (2й аргумент)?

2021-01-24 13:25 UTC, AntiHero commented on src/styles/main.css
> +  flex: 0 0 20vw;
так а почему 0?

2021-01-24 13:25 UTC, AntiHero commented on src/index.html
> +        <p>
а зачем оборачивать в p?

2021-01-24 17:47 UTC, ValentinDankovtsev commented on src/index.html
> +        <p>
ну я подсмотрел у того же днс в футере в <p> обвернуто
https://www.dns-shop.ru/compare/

2021-01-24 17:47 UTC, ValentinDankovtsev commented on src/styles/footer.css
> +  flex: 0 0 20vw;
значение по-умолчанию, если менять будет растягивать

2021-01-24 17:50 UTC, ValentinDankovtsev commented on src/index.html
> +        <h1 class="header__title--main">
удалил только у h1, остальные переделал

2021-01-24 17:51 UTC, ValentinDankovtsev commented on src/index.html
> +          class="header__image--main"
вот здесь попонятней примеры были, переделал)
http://yoksel.github.io/easy-markup/bem-rules/

2021-01-24 17:52 UTC, ValentinDankovtsev commented on src/styles/main.css
> +  flex: 0 0 20vw;
дефолтное значение, иначе растянется

2021-01-24 18:15 UTC, ValentinDankovtsev commented on .gitignore
> +node_modules
сделал

2021-01-24 19:38 UTC, AntiHero requested changes

2021-01-24 19:38 UTC, AntiHero commented on src/index.html
> +          <h2 class="article-title article-title--main">Как выбрать?</h2>
h2 это у тебя элемент верно? и если уже используешь название блока в  элементе,  то используй полностью `article-block__title article-block__title--main`  вот так будет корректней,  и опять же, зачем тут тебе модификатор? не увидел чтобы ты определял для этого элемента стили согласно ему,  нужен ли он значит?

2021-01-24 19:38 UTC, AntiHero commented on src/index.html
> +          <h3 class="article-block__title">
согласно логике почему тогда не добавил сюда модификатор?)) я бы вообще назвал этот элемент  так `article-block__subtitle`, тем самым избавился от нужны присваивать модификаторы

2021-01-24 19:38 UTC, AntiHero commented on src/index.html
> +          <h3 class="article-block__title">Freestyle</h3>
cоответственно тут тоже будет `article-block__subtitle` (или другое твоё название элемента) чтобы было соответствие одинаковых тэгов с одинаковыми стилями

2021-01-24 19:38 UTC, AntiHero commented on src/index.html
> +          <li class="nav-block__item"><a href="#">Инструкции</a></li>
`nav-block__list-item`

2021-01-24 19:38 UTC, AntiHero commented on src/index.html
> +        <h2 class="news-title news-title--main">News</h2>
опять же, нужен тут модификатор? ведь больше нигде `news-title` ты не используешь насколько я вижу

2021-01-24 19:38 UTC, AntiHero commented on src/index.html
> +        <li class="footer-block__item">Я</li>
во что надо li обернуть?)

2021-01-24 19:38 UTC, AntiHero commented on src/index.html
> +        <p>
ты не подсматривай, ты сам думай)развивай фантазию)

2021-01-24 19:42 UTC, AntiHero commented on src/styles/footer.css
> +  flex: 0 0 20vw;
по умолчанию 1
https://www.w3schools.com/cssref/css3_pr_flex.asp

2021-01-25 08:52 UTC, ValentinDankovtsev commented on src/styles/footer.css
> +  flex: 0 0 20vw;
ну в смысле чтобы при сворачивании сжимался блок, если 1 то этого не будет происходить)

2021-01-25 08:53 UTC, ValentinDankovtsev commented on src/index.html
> +          <h2 class="article-title article-title--main">Как выбрать?</h2>
оставил модификаторы только в image и футере значение где контакты

2021-01-25 08:53 UTC, ValentinDankovtsev commented on src/index.html
> +          <h3 class="article-block__title">
плохая логика,согласен)удалил

2021-01-25 08:54 UTC, ValentinDankovtsev commented on src/index.html
> +          <h3 class="article-block__title">Freestyle</h3>
ок

2021-01-25 08:54 UTC, ValentinDankovtsev commented on src/index.html
> +          <li class="nav-block__item"><a href="#">Инструкции</a></li>
ок

2021-01-25 08:54 UTC, ValentinDankovtsev commented on src/index.html
> +        <li class="footer-block__item">Я</li>
в ul

2021-01-25 11:03 UTC, AntiHero requested changes

2021-01-25 11:03 UTC, AntiHero commented on src/index.html
> +        <ul class="footer-block__list-item">
для ul пишешь `footer-block__list` 
для li пишешь ` footer-block__list-item`
либо 
`footer-block-list` и `footer-block-list__item`
или ещё упрощённый вариант
ul `footer-block__list`
li `footer-block__item`

2021-01-25 11:03 UTC, AntiHero commented on src/index.html
> +            <a
линки  (а) можно назвать footer-block__list-item-link либо footer-block__link (название которые логически подходят для  твоих тегов, где ссылка (тэг а) это link

```html
<ul class="footer-block__list">
  <li class="footer-block__list-item">
    <a  class="footer-block__list-link">
```

2021-01-25 11:03 UTC, AntiHero commented on src/index.html
> +        <h1 class="title-main">SNOWBOARDING PRESENTS:"BIG BAND.БЕРИ КАТАЙ"</h1>
`header__title-main` либо `header__title-main title`, где title это класс для общих стилей заголовков, а c помощью `header__title-main` ты задаёшь непосредственно индивидуальный стииль + я бы всё таки подумал как можно избавиться от  оборачивания h1 в div чтобы не плодить  не  нужные классы обёртки

2021-01-25 11:03 UTC, AntiHero commented on src/index.html
> +        <ul class="nav-block__list-item">
`nav-block-list` либо `nav-block__list` не пиши длинные названия классов, когда их можно сделать короче и логически они больше подходят

2021-01-25 11:03 UTC, AntiHero commented on src/index.html
> +        <ul class="footer-block__list-item">
а это зачем в список обернул? и ниже тоже?)
https://www.w3schools.com/html/html_lists.asp

2021-01-25 11:03 UTC, AntiHero commented on src/styles/footer.css
> +.footer-block__item--number {
не забывай про базовый класс, если такк делаешь, что нужно добавить перед этим стилем?
+ если используешь стили для модификатора не увидел у тебя стилей для базового  классса

2021-01-25 15:40 UTC, ValentinDankovtsev commented on src/index.html
> +        <ul class="footer-block__list-item">
не совсем понял(
был блок похожий в nav.
```
<h3 class="nav-block__subtitle">О Cноубордах</h3>
        <ul class="nav-block__list-item">
          <li class="nav-block__item">
            <a href="#">Интересные статьи</a>
          </li>
```
у нас есть блок в котором вложен элемент list-item, потом идет влож. элемент __item/ правила не нарушаем,все логично

2021-01-25 16:10 UTC, ValentinDankovtsev commented on src/index.html
> +        <ul class="nav-block__list-item">
ну хорошо,прост запутался,выше мы делали 
```
<h3 class="nav-block__subtitle">О Cноубордах</h3>
        <ul class="nav-block__list-item">
          <li class="nav-block__item">
            <a href="#">Интересные статьи</a>
          </li>
```

2021-01-25 16:43 UTC, AntiHero commented on src/index.html
> +        <ul class="footer-block__list-item">
правило не нарушаем верно, но зачем тебе писать list-item когда можно  использовать для ul просто list? чем он по сути и является (списком), а item либо list-item использовать для li, тем самым ты с самого начала уже привыкнешь к некой понятной структуре, которую дальше уже просто по памяти будешь использовать при вёрстке

2021-01-25 18:38 UTC, ValentinDankovtsev commented on src/styles/footer.css
> +.footer-block__item--number {
я правильно понял,в данном случае это стиль для ul? в котором находится модификатор

2021-01-25 18:39 UTC, ValentinDankovtsev commented on src/index.html
> +        <ul class="footer-block__list-item">
на перспективу)чтобы потом вдруг что добавлять li)

2021-01-25 18:40 UTC, ValentinDankovtsev commented on src/index.html
> +        <h1 class="title-main">SNOWBOARDING PRESENTS:"BIG BAND.БЕРИ КАТАЙ"</h1>
хорошо, удалю div для заголовка. сделаю margin:auto для него, чтобы выровнять по центру

2021-01-26 11:50 UTC, AntiHero requested changes

2021-01-26 11:50 UTC, AntiHero commented on src/index.html
> +        <ul class="footer-block__list">
убирай ul пожалуйста либо добавляй Discover в li

2021-01-26 11:50 UTC, AntiHero commented on src/index.html
> +          Сервис
то же самое здесь

2021-01-26 11:50 UTC, AntiHero commented on src/styles/header.css
> +.image--main {
`.image.image--main`

2021-01-26 11:50 UTC, AntiHero commented on src/styles/main.css
> +  background: rgb(245, 245, 220);
тут лучше подойдёт `background-color`

2021-01-26 12:59 UTC, ValentinDankovtsev commented on src/index.html
> +        <ul class="footer-block__list">
@AntiHero могу я просто обернуть в span?
мне не нравится такой метод заключать единственный заголовок в li и ul

2021-01-26 13:39 UTC, AntiHero commented on src/index.html
> +        <ul class="footer-block__list">
можешь, но тогда ul убираешь

2021-01-26 15:50 UTC, ValentinDankovtsev commented on src/styles/main.css
> +  background: rgb(245, 245, 220);
ок

2021-01-26 15:50 UTC, ValentinDankovtsev commented on src/index.html
> +          Сервис
исправил на span

2021-01-26 15:50 UTC, ValentinDankovtsev commented on src/index.html
> +        <ul class="footer-block__list">
ok

2021-01-26 17:47 UTC, merged